"""empty message

Revision ID: 6b456967783c
Revises: ffdc0a98111c
Create Date: 2025-03-01 01:57:53.402186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b456967783c'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('option', sa.String(length=50), nullable=False),
    sa.Column('optional_text', sa.String(length=200), nullable=True),
    sa.Column('shift_worked', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employees')
    # ### end Alembic commands ###
