"""empty message

Revision ID: 533b1fd86041
Revises: 6b456967783c
Create Date: 2025-03-01 02:24:18.877619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '533b1fd86041'
down_revision = '6b456967783c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('employees', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('employees', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'employees', 'users', ['user_id'], ['id'])
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_column('employees', 'updated_at')
    op.drop_column('employees', 'created_at')
    op.drop_column('employees', 'user_id')
    # ### end Alembic commands ###
